title:             Game Design Portfolio
email:             abhilash_lr@yahoo.ca
description:       Silent Observations
author:            Abhilash Ravindranath
#url:               "localhost:4000"
url:               "http://gd-asoka.github.io/"
baseurl:

# Social Profiles
#itch_username:  asoka.itch.io
#github_username:   gd-asoka

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
