title:             Axoka Interactive
email:             abhilash_lr@yahoo.ca
description:       Game Design Portfolio
author:            Abhilash Ravindranath
#url:               "localhost:4000"
url:               "gd-asoka.github.io"
baseurl:

# Social Profiles
#twitter_username:  SBootstrap
#github_username:   BlackrockDigital
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          0
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

